name: CI/CD

on:
  push:
    branches:
      - master
      - cicd

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up node using nvm
        uses: dcodeIO/setup-node-nvm@v3.0.0
        with:
          # The node.js version to use according to nvm. Uses the version specified in .nvmrc if omitted.
          node-version: 10
      - run: |
          npm i
      # - run: |
      #     npm run test
      - run: |
          npm run build
      - name: Upload build
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: Build
          # Directory containing files to upload
          path: build

  deploy-staging:
    needs: [build]
    env:
      GITHUB_PAT: ${{ secrets.DEPLOYMENT_PAT }}

    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: Build
          # Destination path
          path: build
      ### setup env-file from secrets
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_API_KEY"
          value: ${{secrets.STAGING_BACKEND_API_KEY}}
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_AUTH_DOMAIN"
          value: ${{secrets.STAGING_BACKEND_PROJECT_ID}}${{'.firebaseapp.com'}}
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_DATABASE_URL"
          value: ${{'https://'}}${{secrets.STAGING_BACKEND_PROJECT_ID}}${{'.firebaseio.com'}}
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_PROJECT_ID"
          value: ${{secrets.STAGING_BACKEND_PROJECT_ID}}
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_STORAGE_BUCKET"
          value: ${{secrets.STAGING_BACKEND_PROJECT_ID}}${{'.appspot.com'}}
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_MESSAGE_SENDER_ID"
          value: ${{secrets.STAGING_BACKEND_MESSAGE_SENDER_ID}}
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_SENDER_APP_ID"
          value: ${{secrets.STAGING_BACKEND_SENDER_APP_ID}}
      - uses: TickX/var-to-dotenv@v1.1.1
        with:
          key: "REACT_APP_BACKEND_MEASUREMENT_ID"
          value: ${{secrets.STAGING_BACKEND_MEASUREMENT_ID}}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          repo: sharemycart/sharemycart
          target_branch: gh-pages
          build_dir: build
          fqdn: app.sharemycart.com
